baseURL = ""
languageCode = "en-us"
title = "Basic Demo Site"


themesDir = "themes"
theme = "lovely"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = "project"
  weight = 100
  includeNewer = true
[[related.indices]]
  name = 'date'
  weight = 10
[[related.indices]]
  name = 'tags'
  weight = 20  
[[related.indices]]
  name = 'keywords'
  weight = 90


# sectionPagesMenu = "main"
[menu]
  [[menu.main]]
    name = "Projects"
    pre = "pen-tool"
    url = "/projects"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "pen-tool"
    url = "/about/"
    weight = 2